name = "duty-finder"
main = "src/worker.ts"
compatibility_date = "2025-08-13"

[vars]
MODEL = "gpt-4o-mini"   # or "o4-mini"
BASELINE_RATE = "0.10"

[ai]
binding = "AI"

[observability]
enabled = true
